#!/usr/bin/env bash
#transfer file 'file' to a server
#scp / path/to/file username@a:/path/to/destination
#handcoded: scp -i ~/.ssh/id_rsa README.md ubuntu@35.229.61.60

#if number of arguments is >= 3
if [ $# -ge 3 ]
then
    if [ $# -eq 3 ]
    then
    # No private key provided
        scp -o StrictHostKeyChecking=no -i $1 $3$2:~/
    else
        # private key provided
        scp -o StrictHostKeyChecking=no -1 $4 $1 $3$2:~/
    fi
else
    echo "usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
