#!/usr/bin/env bash
#fixes a web server to run nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -1 "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache
sudo -u nginx service nginx start